all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /home/ubuntu/temp.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ssl_enabled: true
    ssl_custom_certs: true
    ssl_ca_cert_filepath: "/home/ubuntu/create_certs/temp/ca.crt"
    ssl_signed_cert_filepath: "/home/ubuntu/create_certs/certs/{{inventory_hostname}}.crt"
    ssl_key_filepath: "/home/ubuntu/create_certs/certs/{{inventory_hostname}}.key"
    ssl_mutual_auth_enabled: true

kafka_controller:
  hosts:
    ip-10-0-2-5.us-east-2.compute.internal:
    ip-10-0-2-165.us-east-2.compute.internal:
    ip-10-0-2-43.us-east-2.compute.internal:

kafka_broker:
  hosts:
    ip-10-0-2-139.us-east-2.compute.internal:
    ip-10-0-2-168.us-east-2.compute.internal:
    ip-10-0-2-22.us-east-2.compute.internal:

schema_registry:
  hosts:
    ip-10-0-2-74.us-east-2.compute.internal:

ksql:
  hosts:
    ip-10-0-2-67.us-east-2.compute.internal:

kafka_connect:
  hosts:
    ip-10-0-2-56.us-east-2.compute.internal:
      vars:
        kafka_connect_confluent_hub_plugins:
          - confluentinc/kafka-connect-datagen:0.4.0

control_center:
  hosts:
    ip-10-0-2-228.us-east-2.compute.internal: